### ISSUE TITLE
User is logged out of room but still sees the room as if connected

### ISSUE THREAD

**Issue by cfdp** [cfdp/opeka#107] opened 2017-08-08 13:57 UTC
This error was triggered by entering a chat room as an anonymous user, then disabling the internet connection for a little while.

The reconnection popup disappeared and from the anonymous user side it seemed that the user was reconnected, but on the counselor UI and the logs reported the user was logged out.

This error relates to #94 and was experienced on Firefox 49, Ubuntu 14.04 @alex-bukach

**Comment by alex-bukach** [comment] 2017-10-01 15:54
@benjamin-dk I cannot reproduce it (though I run Firefox 43 and 52 on Windows XP): both counselor side and the logs say nothing about user having logged out. To confirm, is the anonymous send messages into the chat after "reconnection"? If so, does counselor see them? Could attach the screenshots of the logs, anonymous browser console and the counselor chat page? Also, may I ask you to test the things in another browser? The relevant code is at https://github.com/alex-bukach/opeka/tree/reconnect.

I'm going to set up a VM with Ubuntu 14.04 as well, maybe it's reproducible only on Linux.

**Comment by alex-bukach** [comment] 2017-10-01 18:55
@benjamin-dk I have re-tested it on Ubuntu 14.04 and Firefox 47, and it still seems to work correct. Could you please confirm that you can reproduce this issue with https://github.com/alex-bukach/opeka/tree/reconnect? If you can, I'll record a screencast for you, maybe I miss something.

**Comment by benjamin-dk** [comment] 2017-10-04 10:49
I can't reproduce either. Lets close it for now @alex-bukach

**Closed by benjamin-dk** 2017-10-04 10:49 UTC
Labels: BUG
